use_frameworks!

platform :ios, '9.0'

target 'KLCircleProgress_Example' do
  pod 'KLCircleProgress', :path => '../'
  pod 'Masonry'

  target 'KLCircleProgress_Tests' do
    inherit! :search_paths

    
  end
end
